services:
  elk:
    image: sebp/elk
    volumes:
      - ./logs:/logs:cached,noatime,ro
      - ./exported:/exported
      - ./iis.conf:/etc/logstash/conf.d/iis.conf
      - ./pipelines.yml:/opt/logstash/config/pipelines.yml
    ports: 
      - 5601:5601
      - 9200:9200 
      - 5044:5044
